### ISSUE TITLE
Add `operator+=`

### ISSUE THREAD

**Issue by unterumarmung** [unterumarmung/fixed_string#19]
The current version of the `fixed_string` doesn't have `operator+=` overload but it has to.
Additionally, after implementing `operator+=` we can refactor `operator+` overload for `basic_fixed_string` argument.

**Comment by abel-mak** [comment]
Hi, i want to help.

**Comment by unterumarmung** [comment]
You're welcome to, @abel-mak! Open PR, implement the missing functionality and wait for a review :)

**Comment by abel-mak** [comment]
Hey, I read through the code and I'm a little bit stuck, so the _data is std:: array it can't be resized how operator+= should work in this  case, some hints?

**Comment by unterumarmung** [comment]
Lol, you're right, it shouldn't! I don't know what I was thinking when I wrote this issue.
Feel free to try implementing other issues!
