### ISSUE TITLE
Revise default constructor implementation

### ISSUE THREAD

**Issue by unterumarmung** [unterumarmung/fixed_string#20]
Current implementation of default constructor looks like this:
https://github.com/unterumarmung/fixed_string/blob/6a5b2f5ba41e56a5c70b831d0ffa5a549279a777/include/fixed_string.hpp#L122
It can be reimplemented like this
```cpp
constexpr basic_fixed_string() = default;
```
or even it can be not user-provided if compiler is able to generate it

**Comment by GeorgyFirsov** [comment]
Does default `std::array`'s constructor fill an internal buffer with zeros? Default constructor of `std::array` is implicitly generated, so the internal array is default-initialized and it's elements have indeterminate values.

I consider, that a default-constructed string object (no matter if it is a standard string or fixstr::basic_fixed_string) must be empty, i.e. filled with zeros or at least have 0 at the very first position in buffer.

**Comment by unterumarmung** [comment]
I thought it would be zero initialized 
Anyway we can check it
I already have test for this: https://github.com/unterumarmung/fixed_string/blob/master/test/test.cpp#L94-L102
